backend:
  name: github
  repo: RyomaOhtani/decap-cms
  branch: main
  auth_endpoint: "https://github.com/login/oauth/authorize"
  client_id: Ov23liqlg40iJIovXdO4
  client_secret: ce3a2be4dbc18e8dfb6aec1323de2cd30ca96c13

media_folder: "static/images/uploads"
public_folder: "/images/uploads"


i18n:
  locale: "ja"
  messages:
    loading: "読み込み中..."
    newPost: "新しい投稿"
    publish: "公開"
    save: "保存"
    delete: "削除"

collections:
  - name: "blog"
    label: "ブログ"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"
      - label: "本文"
        name: "body"
        widget: "markdown"